In [ ]:
# Initialize Otter
import otter
grader = otter.Notebook("lab04.ipynb")

# E7: Introduction to Computer Programming for Scientists and Engineers

## Lab Assignment 4

For each question, you will have to fill in one or more Python functions. We provide an autograder with a number of test cases that you can use to test your function. Note that the fact that your function works for all test cases thus provided does necessarily guarantee that it will work for all possible test cases relevant to the question. It is your responsibility to test your function thoroughly, to ensure that it will also work in situations not covered by the test cases provided

## Score Breakdown
Question| Points
--- | --
1 | 5.0
2 | 4.0
3 | 4.0
4 | 4.0
5 | 4.0
6 | 4.0
Total | 25.0

In [ ]:
# Please run this cell, and do not modify the contets
import numpy as np
import math
import hashlib
import matplotlib.pyplot as plt
def get_hash(num):
    """Helper function for assessing correctness"""
    return hashlib.md5(str(num).encode()).hexdigest()

## Question 1: Interest

The interest rate, $r$, on a principal investment, $P_0$, is a payment for allowing the bank to use an investor's money. Compound interest is accumulated according to the formula $P_n = (1 + r)P_{n-1}$, where $P_n$ is the balance after $n$ compounding periods (in our case years), and $P_{n-1}$ is the balance after the previous period. The interest rate $r$ is given
in decimal, e.g. 0.1, which is 10%. The objective is to determine the number of years required to reach an investment goal based on an initial investment $P_0$ and an interest rate $r$.

You will need to complete the function below, `mySavingsPlan(P0, r, goal)`, which returns `years`, the number of years required to reach an investment goal. Assume that interest is paid out in one payment at the end of a given year. The output `years` should be a whole number.

Complete the function below to solve the investment problem using a while loop. There are hints to guide you on what is missing on each line.

In [ ]:
# ANSWER CELL
def mySavingsPlan(P0, r, goal):
    """Return number of years required to reach an investment goal based on an initial investment P0 and an interest rate r.
    >>> mySavingsPlan(1000, 0.05, 10000)
    48
    >>> mySavingsPlan(1000, 0.10, 10000)
    25
    >>> mySavingsPlan(1000, 0.05, 1000000)
    142
    """
    # Initialize number of years required to reach investment goal
    years = ...
    
    # Initialize amount of money in the current period
    money = ...
    
    # Add logical expression that should be checked each time you iterate through the loop
    while ...
        
        # Update amount of money in the next period
        money = ...
        
        # Update number of years required to reach investment goal
        years = ...

    return years

Try out your new `mySavingsPlan()` function in the cell below for `P0 = 1000` dollars, `r = 0.05`, and `goal = 10000` dollars. Feel free to try it for other inputs.

You do not need to store any outputs from the cell below. This is just to allow you to test your function.

In [ ]:
grader.check("q1")

## Question 2: Sum Digits

Write a function `mySum(n)` that takes a non-negative integer (`n`) and returns the sum of its digits (`digit_sum`) as an integer. If `n` is negative and/or non-integer, the function should return "Invalid Input." Be careful with your string formatting. Minor differences will result in a failed test.

Note that if `n` has a decimal point but without any fractional component (e.g., 10.0 and 10.), then `n` should be treated as an integer.

*Hint:* Strings are iterable.

```
Examples:

>>> mySum(10) # 1 + 0 = 1
1

>>> mySum(4224) # 4 + 2 + 2 + 4 = 12
12

>>> mySum(1234567890)
45

>>> mySum(-10)
'Invalid Input.'

>>> mySum(10.1)
'Invalid Input.'

>>> mySum(10.0) # 1 + 0 = 1
1

>>> a = mySum(123) # make sure that you are using return rather than print
>>> a
6
```

In [ ]:
# ANSWER CELL
...

Try out your new `mySum()` function in the cell below for `n = 20050`. Feel free to try it for other inputs.

You do not need to store any outputs from the cell below. This is just to allow you to test your function.

In [ ]:
grader.check("q2")

## Question 3: Hailstone

Douglas Hofstadter's Pulitzer-prize-winning book, Gödel, Escher, Bach, poses the following mathematical puzzle.

1. Pick a positive integer `n` as the start.
1. If `n` is even, divide it by 2.
2. If `n` is odd, multiply it by 3 and add 1.
3. Continue this process until `n` is 1.

The number `n` will travel up and down but eventually end at 1 (at least for all numbers that have ever been tried -- nobody has ever proved that the sequence will terminate). Analogously, a hailstone travels up and down in the atmosphere before eventually landing on earth.

This sequence of values of `n` is often called a Hailstone sequence. Write a function `hailstone(n)` that takes a positive integer (`n`) and returns a list of the hailstone sequence starting at `n` (`sequence`) and the number of steps in the sequence (`steps`). The first returned object should be `sequence` and the second returned object should be `steps`.

If `n` is non-positive and/or non-integer, the function should return "Invalid Input." Be careful with your string formatting. Minor differences will result in a failed test. 

Note that if `n == 1` initially, then the sequence is one step long.

```
Examples:

>>> hailstone(10)
([10, 5, 16, 8, 4, 2, 1], 7)

>>> hailstone(1)
([1], 1)

>>> hailstone(9)
([9, 28, 14, 7, 22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1], 20)

>>> hailstone(0)
'Invalid Input.'
```

In [ ]:
# ANSWER CELL
...

Try out your new `hailstone()` function in the cell below for `n = 25`. Feel free to try it for other inputs.

You do not need to store any outputs from the cell below. This is just to allow you to test your function.

In [ ]:
grader.check("q3")

## Question 4: Minimum Searching

Write a function `myMin(P)` that takes a numeric sequence (list, tuple, NumPy array) (`P`) and returns the minimum value in `P` (`value`) and the index(ex) of the minimum value (`loc`), where `loc` should be a list. Note that the minimum value could appear more than once. If this is the case, `loc` should specify the indexes of all occurrences of the minimum value. **You may NOT use the built-in Python function `min()` in your function.**

The first returned object should be `value` and the second returned object should be `loc`.

```
Examples:

>>> myMin([5, 4, 5, 2, 6, 7, 1, 8, 9])
(1, [6])

>>> myMin([2, 3, 5, 7, 2, 4, 3, 2])
(2, [0, 4, 7])

>>> myMin([2, -3, 5, -7, 2, 4, 3, 2])
(-7, [3])

>>> myMin([2, -3, 5, 7, 2, 4, -3, 2])
(-3, [1, 6])
```

In [ ]:
# ANSWER CELL
...

Try out your new `myMin()` function in the cell below for ` P = [2, -3, 5, 7, 2, 4, -3, 2]`. Feel free to try it for other inputs.

You do not need to store any outputs from the cell below. This is just to allow you to test your function.

In [ ]:
grader.check("q4")

## Question 5: Rainfall Totals

Write a function `myRainfall(rainData)` that takes a numeric sequence (list, tuple, NumPy array) of daily rainfall measurements (`rainData`) and returns the total rainfall (`rainTot`) and the average daily rainfall (`rainAvg`) over a period of interest.

The argument `rainData` may contain the number -999 indicating the end of the data from a given period. We are interested in computing the total and average daily rainfall over the first period only (everything after the first -999 should be ignored). There may be negative numbers other than -999 in`rainData`, which represent erroneous measurements and should be neglected.

Your function `myRainfall(rainData)` should return `rainTot` and `rainAvg`, which are the total and average of the non-negative values in either the entire input `rainData` or the period from the beginning until the first occurrence of -999. Note that `rainAvg` is the average daily rainfall during this period (not counting days with neglected measurements). The first returned object should be `rainTot` and the second returned object should be `rainAvg`.

```
Examples:

>>> myRainfall([2, 4, -5, 1, 7, -2, 8, -999, 4, 6, 4])
(22, 4.4)

>>> myRainfall([2, 4, -5, 1, 7, -2, 8, 0, 4, 6, 4])
(36, 4.0)

>>> myRainfall([2, 4, -999, 1, 7, -2, 8, -999, 4, 6, 4])
(6, 3.0)

>>> myRainfall([0, -999, -5, 1, 7, -2, 8, -999, 4, 6, 2])
(0, 0.0)
```

In [ ]:
# ANSWER CELL
...

Try out your new `myRainfall()` function in the cell below for ` rainData = [2.3, 4.1, -5.4, 1.0, 7.1, -2, 8, 0, 4.9, 6, -999]`. Feel free to try it for other inputs.

You do not need to store any outputs from the cell below. This is just to allow you to test your function.

In [ ]:
grader.check("q5")

## Question 6: Summation Target

Write a function that takes a list of numbers (`myList`) and a single desired value to serve as a target summation (`sumTarget`). Your function needs to find all unique three elements $a, b, c$ in `myList` such that $a + b + c$ = `sumTarget`. 

Your function `mySummation(myList, sumTarget)` should return `results`, where `results` is a NumPy array with shape (M, 3), where each row includes unique three elements $a, b, c$ in `myList` that add up to `sumTarget`. 

Constraints:
* In `results`, the three elements $a, b, c$ within each row should be sorted in ascending order. 
* The order of the unique triplets (i.e., order of rows) does not matter.
* No duplicate rows should be present in `results` (each row should be unique).
* If no three elements add up to `sumTarget`, the function should return an empty array: `[]`.
* Within each row, the same element cannot be selected more than once, unless it appears in `myList` more than once (i.e., selecting elements is done without replacement).

*Hint:* You may find [`numpy.vstack()`](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) and [`numpy.empty()`](https://numpy.org/doc/stable/reference/generated/numpy.empty.html) useful for creating your `results` array.


```
Examples:

>>> mySummation([1, 1, 5, 6, 7, 8, 10], 10)
array([[1., 1., 8.]])

>>> mySummation([0, 1, 1, 2, 3, 4], 5)
array([[0., 1., 4.],
       [0., 2., 3.],
       [1., 1., 3.]])
       
>>> mySummation([0, 1, 1, 2, 3, 4], 10)
array([], dtype=float64)

>>> mySummation([0.1, 0.5, -1, 2, 4, 3.3], -0.4)
array([[-1. ,  0.1,  0.5]])
```

In [ ]:
# ANSWER CELL
...

Try out your new `mySummation()` function in the cell below for `array = [0, 1, 1, 2, 3, 4]` and `sumTarget = 8`. Feel free to try it for other inputs.

You do not need to store any outputs from the cell below. This is just to allow you to test your function.

In [ ]:
grader.check("q6")

In [ ]:
import matplotlib.image as mpimg
img = mpimg.imread('resources/animal.png')
imgplot = plt.imshow(img)
imgplot.axes.get_xaxis().set_visible(False)
imgplot.axes.get_yaxis().set_visible(False)
print("Congrats on finishing lab 4 on branching and iteration!")
plt.show()

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

Make sure you submit the .zip file to Gradescope.

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export()